options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: node
    entrypoint: npm
    args: ['install']

  - name: node
    entrypoint: npm
    args: ['run', 'build']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gsutil
      - -m
      - rsync
      - -r
      - -c
      - -d
      - dist/
      - gs://attendance-frontend-static-site/

availableSecrets:
  secretManager:
    - versionName: projects/tsmc-attendance-system-458811/secrets/API_URL/versions/latest
      env: 'VITE_API_BASE_URL'
