options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: node
    entrypoint: npm
    args: ['install']

  - name: node
    entrypoint: bash
    args:
      - -c
      - |
        echo "Using VITE_API_BASE_URL=$$VITE_API_BASE_URL"
        VITE_API_BASE_URL=$$VITE_API_BASE_URL npm run build
        echo "Build Finished,dist/ ："
        ls -lh dist/
    secretEnv: ['VITE_API_BASE_URL']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gsutil -m rsync -r -c -d dist/ gs://attendance-frontend-static-site/
        gsutil cp dist/index.html gs://attendance-frontend-static-site/index.html
        echo "Deployed time: $(date)"

availableSecrets:
  secretManager:
    - versionName: projects/tsmc-attendance-system-458811/secrets/API_URL/versions/latest
      env: 'VITE_API_BASE_URL'
